name: Node CI

on:
  pull_request:
    branches:
      - main
env:
  DB_URL: ${{ secrets.DB_URL }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install server dependencies
        run: cd server && npm i

      - name: Run server tests
        run: cd server && npm test

      - name: Install client dependencies
        run: cd client && npm i

      - name: Run client tests
        run: cd client && npm test